"""create requests table

Revision ID: 60c1b352831b
Revises: a9a3e3dc5938
Create Date: 2025-12-28 20:38:35.809898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c1b352831b'
down_revision: Union[str, None] = 'a9a3e3dc5938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('assigned_contractor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('CONSTRUCTION', 'RENOVATION', 'PLUMBING', 'ELECTRICAL', 'PAINTING', 'FLOORING', 'ROOFING', 'LANDSCAPING', 'INTERIOR_DESIGN', 'OTHER', name='requestcategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='requeststatus'), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('preferred_start_date', sa.DateTime(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_contractor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_assigned_contractor_id'), 'requests', ['assigned_contractor_id'], unique=False)
    op.create_index(op.f('ix_requests_category'), 'requests', ['category'], unique=False)
    op.create_index(op.f('ix_requests_city'), 'requests', ['city'], unique=False)
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_society_id'), 'requests', ['society_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_title'), 'requests', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_title'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_society_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_index(op.f('ix_requests_city'), table_name='requests')
    op.drop_index(op.f('ix_requests_category'), table_name='requests')
    op.drop_index(op.f('ix_requests_assigned_contractor_id'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
